version: "3.9"

services:
  windows-runner-vm:
    image: docker.io/vaggeliskls/windows-ci-custom-runner:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env
    stdin_open: true
    tty: true
    privileged: true
    # runtime: nvidia
    ports:
      - 3389:3389
    deploy:
      replicas: 1
