version: "3.9"

services:
  win10:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: win10
    hostname: win10
    env_file: .env
    stdin_open: true
    tty: true
    privileged: true
    # runtime: nvidia
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    devices:
      - /dev/kvm
      - /dev/net/tun
    ports:
      - 3389:3389
    networks:
      win10-net:
        ipv4_address: 10.1.1.16

networks:
  win10-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1
