version: "3.9"

services:
  win10:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env
    stdin_open: true
    tty: true
    privileged: true
    # runtime: nvidia
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    devices:
      - /dev/kvm
      - /dev/net/tun
    ports:
      - 3389:3389
    deploy:
      replicas: 1
