version: "3.9"

services:
  windows-github-runner-vm:
    image: docker.io/vaggeliskls/windows-github-custom-runner:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env
    stdin_open: true
    tty: true
    privileged: true
    cgroup: host
    restart: always
    volumes:
      - ./Vagrantfile:/app/Vagrantfile
    # runtime: nvidia
    ports:
      - 3389:3389
      - 2222:2222
