name: Windows custom runner

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  TAG_NAME: ${{ github.ref_name }}

jobs:
  publish-image:
    runs-on: ubuntu-latest
    name: publish image
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest,${{ env.REGISTRY }}/${{ github.repository }}:${{ env.TAG_NAME }}